### ISSUE TITLE
Python os.path.realpath() when using mount manager mount

### ISSUE THREAD

**Issue by chaimmintz** [winfsp/winfsp#441]
I am using 1.12b1 and using a mount that uses the mount manager (ex: `\\.\c:\temp\winfspmount`). I am encountering an issue that Python (3.8.13) os.path.realpath() returns something like `\Device\Volume{<guid>}\winfspmount\foo` but that doesn't seem to be path that python/windows recognizes as a valid path, so os.path.exists() returns false.

So it seems this leads to a weird situation that:
```
my_file="c:\\temp\\winfspmount\\foo"
os.path.exists(my_file) -> returns true
os.path.exists(os.path.realpath(my_file)) -> returns false
```

afaik `os.path.realpath` is just supposed to be resolving symlinks, so i would expect `os.path.realpath` in this case to just return the same path, and not `\Device\Volume{<guid>}\...`. (tbh I am fine with it resovling to anything as long as it is a valid path that python/windows understands later on.)

It seems like this happens because python traverses upwards trying to resolve symlinks ([_getfinalpathname_nonstrict](https://github.com/python/cpython/blob/3.8/Lib/ntpath.py#L579)) using python's `nt.readlink` and `nt.readlink("<winfsp mount>")` returns the `\Device\Volume{<guid>}` string.

Is there anything that can be done about this?

**Comment by chaimmintz** [comment]
fwiw java17 internals somewhere `WindowsLinkSupport.getRealPath` also isn't happy with these directory mount points (but is fine with drive mount points), it complains the files is not there when the file is certainly there.

 Caused by: java.nio.file.NoSuchFileException: C:\my\winfsp\mount\foo.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsLinkSupport.getFinalPath(WindowsLinkSupport.java:82)
	at java.base/sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:241)
	at java.base/sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:933)
	at java.base/sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:42)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)

**Comment by billziss-gh** [comment]
The `GetFinalPathNameByHandleW` API works with latest Beta of WinFsp (2022.2 Beta1) when using mount manager drives or directories.

Furthermore before releasing the latest beta I did check that Python (3.8.3 on my system) was able to correctly resolve paths using the repro step from #427. Perhaps this area of the Python libraries was changed recently to reintroduce the problem.

**Comment by billziss-gh** [comment]
Here is a demo that this works with memfs and Python 3.8.3 on my system:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/15330948/189882958-b1b1cb11-6c8a-4071-ab07-a35bbade1297.png">

**Comment by chaimmintz** [comment]
What does `dir c:\users\billziss` show for the `mnt` directory? Does it show it as a junction with a `\Device\Volume{guid}` target?

**Comment by chaimmintz** [comment]
Ok I did further testing - mounting via memfs does show as a `\Device\Volume{guid}` junction and os.path.realpath does work and return the original path. However when I use the winfsp fuse api to to create a mount i also see it as a function with a target of `\Device\Volume{guid}` but os.path.realpath (same exact version of python) returns that `\Device\Volume{guid}` as the path. I am passing in the path as `\\.\c:\foo\bar` so it should be using the mount manager.
1. how can i verify that it is indeed using the mount manager
2. does memfs use the fuse interface or raw winfsp? any idea why the behavior would differ?

**Comment by billziss-gh** [comment]
The MEMFS file system uses the native WinFsp API and not FUSE.

However [`MEMFS-FUSE`](https://github.com/winfsp/winfsp/tree/master/tst/memfs-fuse) also works correctly with Mount Manager directories.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/15330948/190145159-e5c0663c-6d1e-45cc-bcba-55ace9262dde.png">

**Comment by chaimmintz** [comment]
How can I verify that my mount is actually using the mount manager?

**Comment by billziss-gh** [comment]
I cannot remember the command of the top of my head. Maybe `fsutil volume list`.

Is your file system Cygwin based?

**Comment by billziss-gh** [comment]
@chaimmintz 

If your file system is based on Cygwin there is the possibility that some path massaging that happens on Cygwin only, removes the leading `\\.\` from the path and thus makes your file system inadvertently not use the Mount Manager.

If your file system is not based on Cygwin then the problem must be something else.

Please confirm one way or another.

**Comment by billziss-gh** [comment]
I have added commit ea189c5b683b25eeca0cdb60fd12e27536db1c01 that fixes this issue for Cygwin based FUSE file systems.

Since this was already working for native and (non-Cygwin) FUSE file systems, I am closing this issue.
